# app:
#    resource: "@AppBundle/Controller/"
#s    type:     annotation
default:
    path: /
    defaults: {_controller: AppBundle:Main:welcome}

welcome:
    path: /welcome
    defaults: {_controller: AppBundle:Main:welcome}

login:
    path: /login
    defaults: {_controller: AppBundle:Security:login}

active:
    path: /user/active
    defaults: {_controller: AppBundle:Main:active}


homepage:
    path: /user/
    defaults: {_controller: AppBundle:Main:home}

logout:
    path: /logout

add:
    path: /add
    methods:  [POST]
    defaults: {_controller: AppBundle:Main:add}

map:
    path: /user/map
    defaults: {_controller: AppBundle:Main:map}

table:
    path: /user/table
    defaults: {_controller: AppBundle:Main:table}

update:
    path: /user/update
    defaults: {_controller: AppBundle:Main:updateGeo}

setting:
    path: /user/setting
    defaults: {_controller: AppBundle:Main:setting}

user_registration:
    path: /register
    defaults: {_controller: AppBundle:Registration:register}
Ajax_active:
    path: /user/ajax/active
    defaults: {_controller: AppBundle:Main:activationSwitch}
