# app:
#    resource: "@AppBundle/Controller/"
#s    type:     annotation

#default:
#    path: /
#    defaults: {_controller: AppBundle:Main:welcome}

about:
    path: /about
    defaults: {_controller: AppBundle:Main:welcome}

login:
    path: /login
    defaults: {_controller: AppBundle:Security:login}

homepage:
    path: /
    defaults: {_controller: AppBundle:Main:home}

logout:
    path: /logout

add:
    path: /add
    methods:  [POST]
    defaults: {_controller: AppBundle:Main:add}

map:
    path: /map
    defaults: {_controller: AppBundle:Main:map}

table:
    path: /table
    defaults: {_controller: AppBundle:Main:table}

update:
    path: /update
    defaults: {_controller: AppBundle:Main:updateGeo}

setting:
    path: /setting
    defaults: {_controller: AppBundle:Main:setting}

user_registration:
    path: /register
    defaults: {_controller: AppBundle:Registration:register}
Ajax_active:
    path: /ajax/active
    defaults: {_controller: AppBundle:Main:activationSwitch}

post_test:
    path: /test
    defaults: {_controller: AppBundle:Main:postTest}

